# Generated by Django 4.0.6 on 2022-07-22 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_status'),
        ('post', '0005_jobpostactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.status'),
        ),
    ]
