# Generated by Django 4.0.6 on 2022-07-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_jobpostactivity_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
