# Generated by Django 4.0.6 on 2022-07-22 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_jobemployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='employment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.jobemployment'),
        ),
    ]
