# Generated by Django 4.0.6 on 2022-07-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_status_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
